//! Derive rendering.

mod bitfield;
mod r#enum;
mod r#struct;

use super::model::WireType;
use proc_macro2::TokenStream;

pub(super) fn render(model: WireType, runtime: &TokenStream) -> syn::Result<TokenStream> {
    match model {
        WireType::Struct(model) => r#struct::render(model, runtime),
        WireType::Enum(model) => r#enum::render(model, runtime),
        WireType::Bitfield(model) => bitfield::render(model, runtime),
    }
}

/// Returns the generated bytes-backed view path for a direct nested wire type.
fn generated_view_path(ty: &syn::Type) -> syn::Result<TokenStream> {
    let syn::Type::Path(type_path) = ty else {
        return Err(syn::Error::new_spanned(
            ty,
            "nested wire fields must use a direct type path",
        ));
    };
    if type_path.qself.is_some() {
        return Err(syn::Error::new_spanned(
            ty,
            "qualified nested wire types are not supported",
        ));
    }
    let mut segments = type_path.path.segments.iter().peekable();
    let mut path = TokenStream::new();
    while let Some(segment) = segments.next() {
        if segments.peek().is_some() {
            path.extend(quote::quote!(#segment::));
        } else {
            let view = quote::format_ident!("{}View", segment.ident);
            path.extend(quote::quote!(#view));
        }
    }
    if path.is_empty() {
        return Err(syn::Error::new_spanned(
            ty,
            "nested wire type path is empty",
        ));
    }
    Ok(path)
}
