[workspace]
members = ["wire-repr", "wire-repr-macros"]
resolver = "3"

[workspace.package]
version = "0.6.0"
edition = "2024"
rust-version = "1.91"
license = "MIT"
repository = "https://github.com/SilentBless/wire-repr-rs"
homepage = "https://github.com/SilentBless/wire-repr-rs"

[workspace.dependencies]
proc-macro2 = { version = "1", default-features = false, features = ["proc-macro"] }
quote = { version = "1", default-features = false }
syn = { version = "2", default-features = false, features = ["full", "parsing", "printing", "proc-macro"] }
wire-repr-macros = { path = "wire-repr-macros", version = "0.6.0" }

[workspace.lints.rust]
unsafe_code = "deny"
