//! Hidden runtime support for generated recursive views.

use crate::{ArrayError, Frame, InvalidFrameExtent, LayoutError, NeedMore, TrailingBytes};

/// Recursive representation exceeded the caller-selected depth.
#[derive(Clone, Copy, Debug, Eq, PartialEq, thiserror::Error)]
#[error("recursive depth {limit} exceeded at absolute offset {offset}")]
pub struct DepthExceeded {
    /// Caller-selected maximum nesting depth.
    pub limit: usize,
    /// Absolute offset of the first representation beyond the limit.
    pub offset: usize,
}

/// Runtime depth budget propagated through generated recursive framing.
#[doc(hidden)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RecursiveDepth {
    remaining: usize,
    limit: usize,
}

impl RecursiveDepth {
    /// Creates a finite caller-selected budget.
    #[must_use]
    pub const fn new(limit: usize) -> Self {
        Self {
            remaining: limit,
            limit,
        }
    }

    /// Returns the configured limit.
    #[must_use]
    pub const fn limit(self) -> usize {
        self.limit
    }

    /// Returns levels still available below the current parent.
    #[must_use]
    pub const fn remaining(self) -> usize {
        self.remaining
    }

    /// Enters one root and returns the budget available to its body.
    pub fn enter(self, offset: usize) -> Result<Self, DepthExceeded> {
        if self.remaining == 0 {
            return Err(DepthExceeded {
                limit: self.limit,
                offset,
            });
        }
        Ok(Self {
            remaining: self.remaining - 1,
            limit: self.limit,
        })
    }
}

/// Finite error shared by recursively repeated child boundaries.
#[doc(hidden)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, thiserror::Error)]
pub enum RecursiveError {
    /// Input ended before a representation could be framed.
    #[error(transparent)]
    NeedMore(#[from] NeedMore),
    /// Required physical geometry could not be represented.
    #[error(transparent)]
    Layout(#[from] LayoutError),
    /// A generated child reported an invalid extent.
    #[error(transparent)]
    InvalidFrame(#[from] InvalidFrameExtent),
    /// Exact framing left bytes inside a declared body.
    #[error(transparent)]
    Trailing(#[from] TrailingBytes),
    /// The caller-selected recursive depth was exceeded.
    #[error(transparent)]
    DepthExceeded(#[from] DepthExceeded),
    /// A schema-specific child failed at this absolute site.
    #[error("recursive child failed at absolute offset {offset}")]
    Child {
        /// Absolute child start.
        offset: usize,
    },
    /// A recursive selector was not recognized.
    #[error("unknown recursive selector at absolute offset {offset}")]
    UnknownSelector {
        /// Absolute selector start.
        offset: usize,
    },
}

/// Flattens generated root errors at recursive repetition boundaries.
#[doc(hidden)]
pub trait FlattenRecursiveError {
    /// Converts the generated error without retaining recursive type nesting.
    fn flatten_recursive(self, fallback_offset: usize) -> RecursiveError;
}

impl<E> FlattenRecursiveError for ArrayError<E>
where
    E: core::error::Error + FlattenRecursiveError + 'static,
{
    fn flatten_recursive(self, fallback_offset: usize) -> RecursiveError {
        match self {
            ArrayError::NeedMore(source) => RecursiveError::NeedMore(source),
            ArrayError::Item { source, .. } => source.flatten_recursive(fallback_offset),
            ArrayError::InvalidExtent {
                consumed,
                available,
                ..
            } => RecursiveError::InvalidFrame(InvalidFrameExtent {
                offset: fallback_offset,
                consumed,
                available,
            }),
            ArrayError::NonProgress { offset, .. } => RecursiveError::Child { offset },
            ArrayError::Trailing { offset, trailing } => {
                RecursiveError::Trailing(TrailingBytes { offset, trailing })
            }
        }
    }
}
/// Prefix geometry of a recursive counted body.
#[doc(hidden)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RecursiveChildren {
    /// Number of recursive roots in the body.
    pub count: u32,
    /// Bytes before the first child.
    pub prefix: usize,
}

/// Resolves a generated recursive slot without reconstructing hidden item names.
#[doc(hidden)]
pub trait RecursiveSlot<const INDEX: usize> {
    /// Hidden marker selected for this concrete body instantiation.
    type Marker;
}

/// Statically dispatched recursive-root callback generated by the root enum.
#[doc(hidden)]
#[allow(unsafe_code)]
pub trait RecursiveFrame<Slot> {
    /// Recursive schema root.
    type Root;
    /// Finite state for one root.
    type State: 'static;
    /// Finite generated root error.
    type Error: core::error::Error + FlattenRecursiveError + 'static;
    /// Ordinary generated root view family.
    type View<'view, const DEPTH: usize>: AsRef<[u8]>;

    /// Frames one root after its depth level has already been entered.
    fn frame<const DEPTH: usize>(
        input: &[u8],
        absolute_offset: usize,
        body_depth: RecursiveDepth,
    ) -> Result<Frame<Self::State>, Self::Error>;

    /// Skips exactly one root through an iterative generated grammar machine.
    fn skip<const DEPTH: usize>(
        input: &[u8],
        absolute_offset: usize,
        depth: RecursiveDepth,
    ) -> Result<usize, Self::Error>;

    /// Reconstructs the same generated root view family over one exact item span.
    ///
    /// # Safety
    /// `state` must come from `frame` over `input` with the supplied offset and body depth.
    unsafe fn into_view<'view, const DEPTH: usize>(
        input: &'view [u8],
        state: Self::State,
        absolute_offset: usize,
        body_depth: RecursiveDepth,
    ) -> Self::View<'view, DEPTH>;
}

/// Hidden recursive framing surface generated for a generic body slot.
#[doc(hidden)]
#[allow(unsafe_code)]
pub trait RecursiveBody<C, Slot>: Sized {
    /// Finite local body state. Recursive child states are never retained here.
    type State: 'static;
    /// Finite body error.
    type Error: core::error::Error + 'static;
    /// Body view borrowing the immutable root item span.
    type View<'view, const DEPTH: usize>: AsRef<[u8]>;

    /// Decodes the count and child-start prefix without traversing children.
    fn recursive_children(
        input: &[u8],
        absolute_offset: usize,
    ) -> Result<RecursiveChildren, Self::Error>;

    /// Frames the complete body and builds compact exact item geometry.
    fn frame_recursive<const DEPTH: usize>(
        input: &[u8],
        absolute_offset: usize,
        depth: RecursiveDepth,
    ) -> Result<Frame<Self::State>, Self::Error>
    where
        C: RecursiveFrame<Slot>;

    /// Reconstructs the body view from its exact span and finite state.
    ///
    /// # Safety
    /// `state` must come from `frame_recursive` for this exact body span.
    unsafe fn from_recursive_parts<'view, const DEPTH: usize>(
        input: &'view [u8],
        state: &'view Self::State,
        absolute_offset: usize,
        depth: RecursiveDepth,
    ) -> Self::View<'view, DEPTH>
    where
        C: RecursiveFrame<Slot>;
}

const GEOMETRY_PERIOD: usize = 64;
const GEOMETRY_REPLAY: u8 = 0;
const GEOMETRY_FIXED: u8 = 1;
const GEOMETRY_PERIODIC: u8 = 2;

/// Compact exact geometry retained for one recursive array.
#[doc(hidden)]
#[derive(Clone)]
pub struct RecursiveGeometry {
    widths: [u8; GEOMETRY_PERIOD],
    run_len: u32,
    cycle_bytes: u32,
    fixed_width: u16,
    period: u8,
    kind: u8,
}

impl RecursiveGeometry {
    /// Reports the selected exact lookup strategy for diagnostics and measurement.
    #[doc(hidden)]
    #[must_use]
    pub const fn kind(&self) -> &'static str {
        match self.kind {
            GEOMETRY_FIXED => "fixed",
            GEOMETRY_PERIODIC => "periodic",
            GEOMETRY_REPLAY => "replay",
            _ => "invalid",
        }
    }
    fn span<C, Slot, const DEPTH: usize>(
        &self,
        input: &[u8],
        count: usize,
        offset: usize,
        depth: RecursiveDepth,
        requested: usize,
    ) -> Result<Option<core::ops::Range<usize>>, ArrayError<RecursiveError>>
    where
        C: RecursiveFrame<Slot>,
    {
        if requested >= count {
            return Ok(None);
        }

        let direct = match self.kind {
            GEOMETRY_FIXED => {
                let width = usize::from(self.fixed_width);
                let start = requested
                    .checked_mul(width)
                    .ok_or(ArrayError::InvalidExtent {
                        index: requested,
                        consumed: usize::MAX,
                        available: input.len(),
                    })?;
                Some(start..start + width)
            }
            GEOMETRY_PERIODIC => {
                let period = usize::from(self.period);
                let run = requested / self.run_len as usize;
                let class = run % period;
                let cycles = run / period;
                let prefix = self.widths[..class]
                    .iter()
                    .map(|width| usize::from(*width))
                    .sum::<usize>();
                let width = usize::from(self.widths[class]);
                let start = cycles * self.cycle_bytes as usize * self.run_len as usize
                    + prefix * self.run_len as usize
                    + requested % self.run_len as usize * width;
                Some(start..start + width)
            }
            GEOMETRY_REPLAY => None,
            _ => unreachable!("generated geometry kind"),
        };
        if let Some(range) = direct {
            return Ok(Some(range));
        }

        let mut cursor = 0usize;
        for index in 0..=requested {
            let absolute = offset
                .checked_add(cursor)
                .ok_or(ArrayError::InvalidExtent {
                    index,
                    consumed: usize::MAX,
                    available: input.len().saturating_sub(cursor),
                })?;
            let consumed =
                C::skip::<DEPTH>(&input[cursor..], absolute, depth).map_err(|source| {
                    ArrayError::Item {
                        index,
                        source: source.flatten_recursive(absolute),
                    }
                })?;
            if consumed == 0 {
                return Err(ArrayError::NonProgress {
                    index,
                    offset: absolute,
                });
            }
            let end = cursor
                .checked_add(consumed)
                .ok_or(ArrayError::InvalidExtent {
                    index,
                    consumed,
                    available: input.len().saturating_sub(cursor),
                })?;
            if end > input.len() {
                return Err(ArrayError::InvalidExtent {
                    index,
                    consumed,
                    available: input.len().saturating_sub(cursor),
                });
            }
            if index == requested {
                return Ok(Some(cursor..end));
            }
            cursor = end;
        }
        unreachable!("requested index is bounded")
    }
}

/// In-place geometry accumulator used only while framing one array.
#[doc(hidden)]
pub struct RecursiveGeometryBuilder {
    observed: [u8; GEOMETRY_PERIOD],
    candidates: u64,
    run_count: usize,
    current_width: usize,
    current_len: u32,
    common_run_len: u32,
    fixed_width: Option<usize>,
    started: bool,
    failed: bool,
}

impl RecursiveGeometryBuilder {
    /// Creates an empty geometry accumulator.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            observed: [0; GEOMETRY_PERIOD],
            candidates: u64::MAX,
            run_count: 0,
            current_width: 0,
            current_len: 0,
            common_run_len: 0,
            fixed_width: None,
            started: false,
            failed: false,
        }
    }

    /// Observes one exact item width.
    pub fn push(&mut self, width: usize) {
        self.fixed_width = match self.fixed_width {
            None => Some(width),
            Some(previous) if previous == width => Some(previous),
            Some(_) => Some(usize::MAX),
        };
        if !self.started {
            self.started = true;
            self.current_width = width;
            self.current_len = 1;
        } else if self.current_width == width {
            self.current_len += 1;
        } else {
            self.finish_run(false);
            self.current_width = width;
            self.current_len = 1;
        }
    }

    /// Finishes the exact compact geometry or a replay marker.
    #[must_use]
    pub fn finish(mut self) -> RecursiveGeometry {
        if self.started {
            self.finish_run(true);
        }
        if let Some(width) = self.fixed_width
            && width != usize::MAX
            && let Ok(width) = u16::try_from(width)
        {
            return RecursiveGeometry {
                widths: [0; GEOMETRY_PERIOD],
                run_len: 0,
                cycle_bytes: 0,
                fixed_width: width,
                period: 0,
                kind: GEOMETRY_FIXED,
            };
        }
        if !self.failed {
            let period = (1..=self.run_count.min(GEOMETRY_PERIOD))
                .find(|period| self.candidates & (1u64 << (period - 1)) != 0);
            if let Some(period) = period {
                let mut widths = [0u8; GEOMETRY_PERIOD];
                let mut cycle_bytes = 0u32;
                for (index, width) in widths.iter_mut().enumerate().take(period) {
                    *width = self.observed[index];
                    cycle_bytes += u32::from(*width);
                }
                return RecursiveGeometry {
                    widths,
                    run_len: self.common_run_len,
                    cycle_bytes,
                    fixed_width: 0,
                    period: period as u8,
                    kind: GEOMETRY_PERIODIC,
                };
            }
        }
        RecursiveGeometry {
            widths: [0; GEOMETRY_PERIOD],
            run_len: 0,
            cycle_bytes: 0,
            fixed_width: 0,
            period: 0,
            kind: GEOMETRY_REPLAY,
        }
    }

    fn finish_run(&mut self, final_run: bool) {
        let Ok(width) = u8::try_from(self.current_width) else {
            self.failed = true;
            return;
        };
        if self.common_run_len == 0 {
            self.common_run_len = self.current_len;
        } else if (!final_run && self.current_len != self.common_run_len)
            || (final_run && self.current_len > self.common_run_len)
        {
            self.failed = true;
            return;
        }
        let index = self.run_count;
        if index < GEOMETRY_PERIOD {
            self.observed[index] = width;
        }
        for period in 1..=GEOMETRY_PERIOD {
            if index >= period && width != self.observed[index % period] {
                self.candidates &= !(1u64 << (period - 1));
            }
        }
        self.failed |= self.candidates == 0;
        self.run_count += 1;
    }
}

impl Default for RecursiveGeometryBuilder {
    fn default() -> Self {
        Self::new()
    }
}

/// Frames one counted recursive array without retaining per-item states or offsets.
#[doc(hidden)]
pub fn frame_recursive_array_extent<C, Slot, const DEPTH: usize>(
    input: &[u8],
    count: usize,
    offset: usize,
    depth: RecursiveDepth,
) -> Result<(usize, RecursiveGeometry), ArrayError<RecursiveError>>
where
    C: RecursiveFrame<Slot>,
{
    let mut cursor = 0usize;
    let mut geometry = RecursiveGeometryBuilder::new();
    for index in 0..count {
        let absolute = offset
            .checked_add(cursor)
            .ok_or(ArrayError::InvalidExtent {
                index,
                consumed: usize::MAX,
                available: input.len().saturating_sub(cursor),
            })?;
        let consumed = C::skip::<DEPTH>(&input[cursor..], absolute, depth).map_err(|source| {
            ArrayError::Item {
                index,
                source: source.flatten_recursive(absolute),
            }
        })?;
        if consumed == 0 {
            return Err(ArrayError::NonProgress {
                index,
                offset: absolute,
            });
        }
        let end = cursor
            .checked_add(consumed)
            .ok_or(ArrayError::InvalidExtent {
                index,
                consumed,
                available: input.len().saturating_sub(cursor),
            })?;
        if end > input.len() {
            return Err(ArrayError::InvalidExtent {
                index,
                consumed,
                available: input.len().saturating_sub(cursor),
            });
        }
        geometry.push(consumed);
        cursor = end;
    }
    Ok((cursor, geometry.finish()))
}
/// Flattens a recursive array facade error without retaining recursive generic error types.
#[doc(hidden)]
pub fn flatten_recursive_array_error(
    error: ArrayError<RecursiveError>,
    fallback_offset: usize,
) -> RecursiveError {
    match error {
        ArrayError::NeedMore(source) => RecursiveError::NeedMore(source),
        ArrayError::Item { source, .. } => source,
        ArrayError::InvalidExtent {
            consumed,
            available,
            ..
        } => RecursiveError::InvalidFrame(InvalidFrameExtent {
            offset: fallback_offset,
            consumed,
            available,
        }),
        ArrayError::NonProgress { offset, .. } => RecursiveError::Child { offset },
        ArrayError::Trailing { offset, trailing } => {
            RecursiveError::Trailing(TrailingBytes { offset, trailing })
        }
    }
}

/// Replayable recursive array facade yielding the root's ordinary view family.
#[doc(hidden)]
pub struct RecursiveArrayView<'input, 'geometry, C, Slot, const DEPTH: usize>
where
    C: RecursiveFrame<Slot>,
{
    input: &'input [u8],
    count: usize,
    offset: usize,
    depth: RecursiveDepth,
    geometry: &'geometry RecursiveGeometry,
    marker: core::marker::PhantomData<fn() -> (C, Slot)>,
}

impl<'input, 'geometry, C, Slot, const DEPTH: usize>
    RecursiveArrayView<'input, 'geometry, C, Slot, DEPTH>
where
    C: RecursiveFrame<Slot>,
{
    /// Creates a facade over geometry proven by generated body framing.
    ///
    /// # Safety
    /// The span must be the exact concatenation of `count` items framed through `C`.
    #[doc(hidden)]
    #[must_use]
    #[allow(unsafe_code)]
    pub const unsafe fn from_validated_parts(
        input: &'input [u8],
        count: usize,
        offset: usize,
        depth: RecursiveDepth,
        geometry: &'geometry RecursiveGeometry,
    ) -> Self {
        Self {
            input,
            count,
            offset,
            depth,
            geometry,
            marker: core::marker::PhantomData,
        }
    }

    /// Returns the authoritative item count.
    #[must_use]
    pub const fn len(&self) -> usize {
        self.count
    }

    /// Reports whether the array is empty.
    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.count == 0
    }
    /// Reports the exact lookup strategy retained by parent framing.
    #[doc(hidden)]
    #[must_use]
    pub const fn geometry_kind(&self) -> &'static str {
        self.geometry.kind()
    }

    /// Returns one exact recursive root view by ordinal.
    #[allow(unsafe_code)]
    pub fn get(
        &self,
        requested: usize,
    ) -> Result<Option<C::View<'input, DEPTH>>, ArrayError<RecursiveError>> {
        let Some(range) = self.geometry.span::<C, Slot, DEPTH>(
            self.input,
            self.count,
            self.offset,
            self.depth,
            requested,
        )?
        else {
            return Ok(None);
        };
        let absolute = self
            .offset
            .checked_add(range.start)
            .ok_or(ArrayError::InvalidExtent {
                index: requested,
                consumed: usize::MAX,
                available: self.input.len().saturating_sub(range.start),
            })?;
        let body_depth = self
            .depth
            .enter(absolute)
            .map_err(|source| ArrayError::Item {
                index: requested,
                source: RecursiveError::DepthExceeded(source),
            })?;
        let item = &self.input[range.clone()];
        let frame =
            C::frame::<DEPTH>(item, absolute, body_depth).map_err(|source| ArrayError::Item {
                index: requested,
                source: source.flatten_recursive(absolute),
            })?;
        let (state, consumed) = frame.into_parts();
        if consumed != item.len() {
            return Err(ArrayError::InvalidExtent {
                index: requested,
                consumed,
                available: item.len(),
            });
        }
        // SAFETY: `state` came from framing this exact item span and body depth.
        Ok(Some(unsafe {
            C::into_view::<DEPTH>(item, state, absolute, body_depth)
        }))
    }

    /// Starts a fresh forward traversal with one physical cursor.
    #[must_use]
    pub const fn iter(&self) -> RecursiveArrayIter<'input, C, Slot, DEPTH> {
        RecursiveArrayIter {
            input: self.input,
            count: self.count,
            offset: self.offset,
            depth: self.depth,
            index: 0,
            cursor: 0,
            failed: false,
            marker: core::marker::PhantomData,
        }
    }
}

/// Forward iterator over recursively framed root values.
#[doc(hidden)]
pub struct RecursiveArrayIter<'input, C, Slot, const DEPTH: usize>
where
    C: RecursiveFrame<Slot>,
{
    input: &'input [u8],
    count: usize,
    offset: usize,
    depth: RecursiveDepth,
    index: usize,
    cursor: usize,
    failed: bool,
    marker: core::marker::PhantomData<fn() -> (C, Slot)>,
}

impl<'input, C, Slot, const DEPTH: usize> Iterator for RecursiveArrayIter<'input, C, Slot, DEPTH>
where
    C: RecursiveFrame<Slot>,
{
    type Item = Result<C::View<'input, DEPTH>, ArrayError<RecursiveError>>;

    #[allow(unsafe_code)]
    fn next(&mut self) -> Option<Self::Item> {
        if self.failed {
            return None;
        }
        if self.index == self.count {
            if self.cursor == self.input.len() {
                return None;
            }
            self.failed = true;
            return Some(Err(ArrayError::Trailing {
                offset: self.offset.saturating_add(self.cursor),
                trailing: self.input.len() - self.cursor,
            }));
        }
        let index = self.index;
        let absolute = match self.offset.checked_add(self.cursor) {
            Some(absolute) => absolute,
            None => {
                self.failed = true;
                return Some(Err(ArrayError::InvalidExtent {
                    index,
                    consumed: usize::MAX,
                    available: self.input.len().saturating_sub(self.cursor),
                }));
            }
        };
        let body_depth = match self.depth.enter(absolute) {
            Ok(depth) => depth,
            Err(source) => {
                self.failed = true;
                return Some(Err(ArrayError::Item {
                    index,
                    source: RecursiveError::DepthExceeded(source),
                }));
            }
        };
        let available = &self.input[self.cursor..];
        let frame = match C::frame::<DEPTH>(available, absolute, body_depth) {
            Ok(frame) => frame,
            Err(source) => {
                self.failed = true;
                return Some(Err(ArrayError::Item {
                    index,
                    source: source.flatten_recursive(absolute),
                }));
            }
        };
        let (state, consumed) = frame.into_parts();
        if consumed == 0 || consumed > available.len() {
            self.failed = true;
            return Some(Err(ArrayError::InvalidExtent {
                index,
                consumed,
                available: available.len(),
            }));
        }
        let start = self.cursor;
        self.cursor += consumed;
        self.index += 1;
        let item = &self.input[start..self.cursor];
        // SAFETY: state and depth came from framing this exact item.
        Some(Ok(unsafe {
            C::into_view::<DEPTH>(item, state, absolute, body_depth)
        }))
    }
}
