//! Runtime contracts shared by `#[derive(Wire)]` implementations.

use crate::{OutputTooShortError, PreparedLayout};

/// Associates a semantic wire value with its generated read view.
#[doc(hidden)]
pub trait WireViewType {
    /// The typed failure returned while validating this representation.
    type DecodeError<'wire>: core::fmt::Debug + core::fmt::Display;

    /// The generated bytes-backed view for input with lifetime `'wire`.
    #[cfg(not(feature = "bytes"))]
    type View<'wire>: Copy + Clone;

    /// The generated bytes-backed view for owned input.
    #[cfg(feature = "bytes")]
    type View<'wire>: Clone;
}

/// A bytes-backed generated wire view.
#[doc(hidden)]
pub trait WireView<'wire>: Sized {
    /// The typed failure returned while validating the view.
    type DecodeError: core::fmt::Debug + core::fmt::Display;

    /// Validates one leading representation and creates its view.
    #[cfg(not(feature = "bytes"))]
    fn parse_view(input: &'wire [u8]) -> Result<(Self, &'wire [u8]), Self::DecodeError>;

    /// Validates one complete borrowed representation and creates its view.
    #[cfg(not(feature = "bytes"))]
    fn parse_complete(input: &'wire [u8]) -> Result<Self, Self::DecodeError> {
        let input_len = input.len();
        let (view, suffix) = Self::parse_view(input)?;
        if suffix.is_empty() {
            Ok(view)
        } else {
            Err(Self::trailing_bytes_error(view.as_bytes().len(), input_len))
        }
    }

    /// Validates one leading representation from owned input and creates its view.
    #[cfg(feature = "bytes")]
    fn parse_view(input: bytes::Bytes) -> Result<(Self, bytes::Bytes), Self::DecodeError>;

    /// Validates one complete owned representation and creates its view.
    #[cfg(feature = "bytes")]
    fn parse_complete(input: bytes::Bytes) -> Result<Self, Self::DecodeError> {
        let input_len = input.len();
        let (view, suffix) = Self::parse_view(input)?;
        if suffix.is_empty() {
            Ok(view)
        } else {
            Err(Self::trailing_bytes_error(view.as_bytes().len(), input_len))
        }
    }

    /// Builds this view's typed error for trailing input.
    fn trailing_bytes_error(represented: usize, input: usize) -> Self::DecodeError;

    /// Returns this view's exact represented bytes.
    #[cfg(not(feature = "bytes"))]
    fn as_bytes(&self) -> &'wire [u8];

    /// Returns this view's exact represented bytes.
    #[cfg(feature = "bytes")]
    fn as_bytes(&self) -> &[u8];
}

/// Generated semantic validation for a structurally decoded view.
#[doc(hidden)]
pub trait WireViewValidation<'wire> {
    /// The human-owned validation error.
    type ValidationError: core::fmt::Debug + core::fmt::Display;

    /// Validates decoded field and model invariants.
    fn validate(&self) -> Result<(), Self::ValidationError>;

    /// Frames and validates one complete borrowed representation.
    #[cfg(not(feature = "bytes"))]
    #[doc(hidden)]
    fn parse_validated_complete(input: &'wire [u8]) -> Result<Self, Self::ValidationError>
    where
        Self: Sized + WireView<'wire>,
        Self::ValidationError: From<<Self as WireView<'wire>>::DecodeError>,
    {
        let input_len = input.len();
        let (view, suffix) = Self::parse_view(input).map_err(Self::ValidationError::from)?;
        view.validate()?;
        if suffix.is_empty() {
            Ok(view)
        } else {
            Err(Self::ValidationError::from(Self::trailing_bytes_error(
                view.as_bytes().len(),
                input_len,
            )))
        }
    }

    /// Frames and validates one complete owned representation.
    #[cfg(feature = "bytes")]
    #[doc(hidden)]
    fn parse_validated_complete(input: bytes::Bytes) -> Result<Self, Self::ValidationError>
    where
        Self: Sized + WireView<'wire>,
        Self::ValidationError: From<<Self as WireView<'wire>>::DecodeError>,
    {
        let input_len = input.len();
        let (view, suffix) = Self::parse_view(input).map_err(Self::ValidationError::from)?;
        view.validate()?;
        if suffix.is_empty() {
            Ok(view)
        } else {
            Err(Self::ValidationError::from(Self::trailing_bytes_error(
                view.as_bytes().len(),
                input_len,
            )))
        }
    }
}

/// A request to frame one bytes-backed wire view.
#[doc(hidden)]
pub struct ViewRequest<'wire, V> {
    #[cfg(not(feature = "bytes"))]
    input: &'wire [u8],
    #[cfg(feature = "bytes")]
    input: bytes::Bytes,
    view: core::marker::PhantomData<(&'wire (), V)>,
}

/// A request which performs structural framing followed by semantic validation.
#[doc(hidden)]
pub struct ValidatedViewRequest<'wire, V, const VALIDATE: bool = true> {
    #[cfg(not(feature = "bytes"))]
    input: &'wire [u8],
    #[cfg(feature = "bytes")]
    input: bytes::Bytes,
    view: core::marker::PhantomData<(&'wire (), V)>,
}

impl<'wire, V, const VALIDATE: bool> ValidatedViewRequest<'wire, V, VALIDATE> {
    /// Creates a validated view request.
    #[doc(hidden)]
    #[must_use]
    #[cfg(not(feature = "bytes"))]
    pub const fn new(input: &'wire [u8]) -> Self {
        Self {
            input,
            view: core::marker::PhantomData,
        }
    }

    /// Creates a validated view request from owned input.
    #[doc(hidden)]
    #[must_use]
    #[cfg(feature = "bytes")]
    pub fn new(input: bytes::Bytes) -> Self {
        Self {
            input,
            view: core::marker::PhantomData,
        }
    }

    /// Skips semantic validation and retains structural decode errors.
    #[must_use]
    #[cfg(not(feature = "bytes"))]
    pub const fn unchecked(self) -> ViewRequest<'wire, V> {
        ViewRequest::new(self.input)
    }

    /// Skips semantic validation and retains structural decode errors.
    #[must_use]
    #[cfg(feature = "bytes")]
    pub fn unchecked(self) -> ViewRequest<'wire, V> {
        ViewRequest::new(self.input)
    }
}

impl<'wire, V> ViewRequest<'wire, V> {
    /// Creates a view request.
    #[doc(hidden)]
    #[must_use]
    #[cfg(not(feature = "bytes"))]
    pub const fn new(input: &'wire [u8]) -> Self {
        Self {
            input,
            view: core::marker::PhantomData,
        }
    }

    /// Creates a view request from owned input.
    #[doc(hidden)]
    #[must_use]
    #[cfg(feature = "bytes")]
    pub fn new(input: bytes::Bytes) -> Self {
        Self {
            input,
            view: core::marker::PhantomData,
        }
    }
}

impl<'wire, V> ViewRequest<'wire, V>
where
    V: WireView<'wire>,
{
    /// Validates the leading representation and returns its unconsumed suffix.
    #[cfg(not(feature = "bytes"))]
    pub fn with_remainder(self) -> Result<(V, &'wire [u8]), V::DecodeError> {
        V::parse_view(self.input)
    }

    /// Validates the leading representation and returns its owned unconsumed suffix.
    #[cfg(feature = "bytes")]
    pub fn with_remainder(self) -> Result<(V, bytes::Bytes), V::DecodeError> {
        V::parse_view(self.input)
    }

    /// Validates one complete borrowed representation, rejecting trailing input.
    #[cfg(not(feature = "bytes"))]
    pub fn without_trailing(self) -> Result<V, V::DecodeError> {
        V::parse_complete(self.input)
    }

    /// Validates one complete owned representation, rejecting trailing input.
    #[cfg(feature = "bytes")]
    pub fn without_trailing(self) -> Result<V, V::DecodeError> {
        let view = V::parse_complete(self.input)?;
        Ok(view)
    }
}

impl<'wire, V> ValidatedViewRequest<'wire, V, true>
where
    V: WireView<'wire> + WireViewValidation<'wire>,
    V::ValidationError: From<V::DecodeError>,
{
    /// Frames and semantically validates the leading representation.
    #[cfg(not(feature = "bytes"))]
    pub fn with_remainder(self) -> Result<(V, &'wire [u8]), V::ValidationError> {
        let (view, remainder) = V::parse_view(self.input).map_err(V::ValidationError::from)?;
        view.validate()?;
        Ok((view, remainder))
    }

    /// Frames and semantically validates the leading representation from owned input.
    #[cfg(feature = "bytes")]
    pub fn with_remainder(self) -> Result<(V, bytes::Bytes), V::ValidationError> {
        let (view, remainder) = V::parse_view(self.input).map_err(V::ValidationError::from)?;
        view.validate()?;
        Ok((view, remainder))
    }

    /// Frames and semantically validates one complete borrowed representation.
    #[cfg(not(feature = "bytes"))]
    pub fn without_trailing(self) -> Result<V, V::ValidationError> {
        V::parse_validated_complete(self.input)
    }

    /// Frames and semantically validates one complete owned representation.
    #[cfg(feature = "bytes")]
    pub fn without_trailing(self) -> Result<V, V::ValidationError> {
        V::parse_validated_complete(self.input)
    }
}

impl<'wire, V> ValidatedViewRequest<'wire, V, false>
where
    V: WireView<'wire>,
{
    /// Structurally validates the leading representation and returns its suffix.
    #[cfg(not(feature = "bytes"))]
    pub fn with_remainder(self) -> Result<(V, &'wire [u8]), V::DecodeError> {
        V::parse_view(self.input)
    }

    /// Structurally validates the leading owned representation and returns its suffix.
    #[cfg(feature = "bytes")]
    pub fn with_remainder(self) -> Result<(V, bytes::Bytes), V::DecodeError> {
        V::parse_view(self.input)
    }

    /// Structurally validates one complete borrowed representation.
    #[cfg(not(feature = "bytes"))]
    pub fn without_trailing(self) -> Result<V, V::DecodeError> {
        V::parse_complete(self.input)
    }

    /// Structurally validates one complete owned representation.
    #[cfg(feature = "bytes")]
    pub fn without_trailing(self) -> Result<V, V::DecodeError> {
        let view = V::parse_complete(self.input)?;
        Ok(view)
    }
}

/// Invalid framing for a sequence of fixed-width wire views.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FixedViewSequenceError {
    /// The generated item representation has zero width.
    InvalidItemWidth,
    /// Input ends with an incomplete item.
    TrailingPartialItem {
        /// Complete item width.
        item_width: usize,
        /// Bytes left after the last complete item.
        trailing: usize,
    },
}

impl core::fmt::Display for FixedViewSequenceError {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::InvalidItemWidth => {
                formatter.write_str("fixed sequence items must consume bytes")
            }
            Self::TrailingPartialItem {
                item_width,
                trailing,
            } => write!(
                formatter,
                "fixed sequence has {trailing} trailing bytes, fewer than one {item_width}-byte item",
            ),
        }
    }
}

impl core::error::Error for FixedViewSequenceError {}

/// Failure while framing or semantically validating a fixed-width view sequence.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FixedValidatedViewSequenceError<E> {
    /// Sequence framing failed.
    Framing(FixedViewSequenceError),
    /// An item failed semantic validation.
    Item(E),
}

impl<E: core::fmt::Display> core::fmt::Display for FixedValidatedViewSequenceError<E> {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Framing(error) => error.fmt(formatter),
            Self::Item(error) => error.fmt(formatter),
        }
    }
}

impl<E: core::fmt::Debug + core::fmt::Display> core::error::Error
    for FixedValidatedViewSequenceError<E>
{
}

/// An infallible iterator over preframed fixed-width wire views.
#[derive(Clone, Debug)]
pub struct FixedViewIterator<'wire, V> {
    #[cfg(not(feature = "bytes"))]
    chunks: core::slice::ChunksExact<'wire, u8>,
    #[cfg(not(feature = "bytes"))]
    make_view: fn(&'wire [u8]) -> V,
    #[cfg(feature = "bytes")]
    remaining: bytes::Bytes,
    #[cfg(feature = "bytes")]
    item_width: usize,
    #[cfg(feature = "bytes")]
    make_view: fn(bytes::Bytes) -> V,
    #[cfg(feature = "bytes")]
    view: core::marker::PhantomData<&'wire ()>,
}

impl<'wire, V> FixedViewIterator<'wire, V> {
    /// Validates fixed-width sequence framing and creates its iterator.
    #[doc(hidden)]
    #[cfg(not(feature = "bytes"))]
    pub fn new(
        input: &'wire [u8],
        item_width: usize,
        make_view: fn(&'wire [u8]) -> V,
    ) -> Result<Self, FixedViewSequenceError> {
        if item_width == 0 {
            return Err(FixedViewSequenceError::InvalidItemWidth);
        }
        let chunks = input.chunks_exact(item_width);
        let trailing = chunks.remainder().len();
        if trailing != 0 {
            return Err(FixedViewSequenceError::TrailingPartialItem {
                item_width,
                trailing,
            });
        }
        Ok(Self { chunks, make_view })
    }

    /// Validates fixed-width sequence framing and creates its iterator from owned input.
    #[doc(hidden)]
    #[cfg(feature = "bytes")]
    pub fn new(
        input: bytes::Bytes,
        item_width: usize,
        make_view: fn(bytes::Bytes) -> V,
    ) -> Result<Self, FixedViewSequenceError> {
        if item_width == 0 {
            return Err(FixedViewSequenceError::InvalidItemWidth);
        }
        let trailing = input.len() % item_width;
        if trailing != 0 {
            return Err(FixedViewSequenceError::TrailingPartialItem {
                item_width,
                trailing,
            });
        }
        Ok(Self {
            remaining: input,
            item_width,
            make_view,
            view: core::marker::PhantomData,
        })
    }
}

impl<'wire, V> Iterator for FixedViewIterator<'wire, V> {
    type Item = V;

    fn next(&mut self) -> Option<Self::Item> {
        #[cfg(not(feature = "bytes"))]
        {
            self.chunks.next().map(self.make_view)
        }
        #[cfg(feature = "bytes")]
        {
            (!self.remaining.is_empty())
                .then(|| (self.make_view)(self.remaining.split_to(self.item_width)))
        }
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        #[cfg(not(feature = "bytes"))]
        {
            self.chunks.size_hint()
        }
        #[cfg(feature = "bytes")]
        {
            let len = self.remaining.len() / self.item_width;
            (len, Some(len))
        }
    }
}

impl<V> ExactSizeIterator for FixedViewIterator<'_, V> {
    fn len(&self) -> usize {
        #[cfg(not(feature = "bytes"))]
        {
            self.chunks.len()
        }
        #[cfg(feature = "bytes")]
        {
            self.remaining.len() / self.item_width
        }
    }
}

impl<V> core::iter::FusedIterator for FixedViewIterator<'_, V> {}

/// Failure while advancing through a sequence of variable-width wire views.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ViewCursorError<E> {
    /// The next representation was structurally invalid.
    Item(E),
    /// A successful item consumed no bytes and therefore cannot advance a sequence.
    EmptyItem,
}

impl<E: core::fmt::Display> core::fmt::Display for ViewCursorError<E> {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Item(error) => error.fmt(formatter),
            Self::EmptyItem => formatter.write_str("a sequence item consumed no bytes"),
        }
    }
}

impl<E: core::fmt::Debug + core::fmt::Display> core::error::Error for ViewCursorError<E> {}

/// A fail-closed cursor over consecutive variable-width wire views.
#[cfg_attr(not(feature = "bytes"), derive(Copy))]
#[derive(Clone, Debug)]
pub struct ViewCursor<'wire, V> {
    #[cfg(not(feature = "bytes"))]
    remaining: &'wire [u8],
    #[cfg(feature = "bytes")]
    remaining: bytes::Bytes,
    view: core::marker::PhantomData<(&'wire (), V)>,
}

impl<'wire, V> ViewCursor<'wire, V> {
    /// Creates a cursor over `input` without validating an item yet.
    #[doc(hidden)]
    #[must_use]
    #[cfg(not(feature = "bytes"))]
    pub const fn new(input: &'wire [u8]) -> Self {
        Self {
            remaining: input,
            view: core::marker::PhantomData,
        }
    }

    /// Creates a cursor over owned input without validating an item yet.
    #[doc(hidden)]
    #[must_use]
    #[cfg(feature = "bytes")]
    pub fn new(input: bytes::Bytes) -> Self {
        Self {
            remaining: input,
            view: core::marker::PhantomData,
        }
    }

    /// Returns the unconsumed bytes.
    #[must_use]
    #[cfg(not(feature = "bytes"))]
    pub const fn remaining(&self) -> &'wire [u8] {
        self.remaining
    }

    /// Returns the unconsumed bytes.
    #[must_use]
    #[cfg(feature = "bytes")]
    pub fn remaining(&self) -> &[u8] {
        &self.remaining
    }
}

impl<'wire, V> ViewCursor<'wire, V>
where
    V: WireView<'wire>,
{
    /// Validates and returns the next item, or `None` at the exact end.
    ///
    /// An error leaves the cursor at the failing item.
    #[allow(clippy::should_implement_trait)]
    pub fn next(&mut self) -> Result<Option<V>, ViewCursorError<V::DecodeError>> {
        if self.remaining.is_empty() {
            return Ok(None);
        }
        #[cfg(not(feature = "bytes"))]
        let (view, suffix) = V::parse_view(self.remaining).map_err(ViewCursorError::Item)?;
        #[cfg(feature = "bytes")]
        let (view, suffix) =
            V::parse_view(self.remaining.clone()).map_err(ViewCursorError::Item)?;
        if suffix.len() == self.remaining.len() {
            return Err(ViewCursorError::EmptyItem);
        }
        self.remaining = suffix;
        Ok(Some(view))
    }
}

/// A fail-closed cursor which semantically validates each framed item.
#[cfg_attr(not(feature = "bytes"), derive(Copy))]
#[derive(Clone, Debug)]
pub struct ValidatedViewCursor<'wire, V> {
    #[cfg(not(feature = "bytes"))]
    remaining: &'wire [u8],
    #[cfg(feature = "bytes")]
    remaining: bytes::Bytes,
    view: core::marker::PhantomData<(&'wire (), V)>,
}

impl<'wire, V> ValidatedViewCursor<'wire, V> {
    /// Creates a validated cursor over `input` without framing an item yet.
    #[doc(hidden)]
    #[must_use]
    #[cfg(not(feature = "bytes"))]
    pub const fn new(input: &'wire [u8]) -> Self {
        Self {
            remaining: input,
            view: core::marker::PhantomData,
        }
    }

    /// Creates a validated cursor over owned input without framing an item yet.
    #[doc(hidden)]
    #[must_use]
    #[cfg(feature = "bytes")]
    pub fn new(input: bytes::Bytes) -> Self {
        Self {
            remaining: input,
            view: core::marker::PhantomData,
        }
    }

    /// Returns the unconsumed bytes.
    #[must_use]
    #[cfg(not(feature = "bytes"))]
    pub const fn remaining(&self) -> &'wire [u8] {
        self.remaining
    }

    /// Returns the unconsumed bytes.
    #[must_use]
    #[cfg(feature = "bytes")]
    pub fn remaining(&self) -> &[u8] {
        &self.remaining
    }

    /// Skips semantic validation for the remaining items.
    #[must_use]
    #[cfg(not(feature = "bytes"))]
    pub const fn unchecked(self) -> ViewCursor<'wire, V> {
        ViewCursor::new(self.remaining)
    }

    /// Skips semantic validation for the remaining items.
    #[must_use]
    #[cfg(feature = "bytes")]
    pub fn unchecked(self) -> ViewCursor<'wire, V> {
        ViewCursor::new(self.remaining)
    }
}

impl<'wire, V> ValidatedViewCursor<'wire, V>
where
    V: WireView<'wire> + WireViewValidation<'wire>,
    V::ValidationError: From<V::DecodeError>,
{
    /// Validates and returns the next item, or `None` at the exact end.
    ///
    /// An error leaves the cursor at the failing item.
    #[allow(clippy::should_implement_trait)]
    pub fn next(&mut self) -> Result<Option<V>, ViewCursorError<V::ValidationError>> {
        if self.remaining.is_empty() {
            return Ok(None);
        }
        #[cfg(not(feature = "bytes"))]
        let (view, suffix) = V::parse_view(self.remaining)
            .map_err(|error| ViewCursorError::Item(V::ValidationError::from(error)))?;
        #[cfg(feature = "bytes")]
        let (view, suffix) = V::parse_view(self.remaining.clone())
            .map_err(|error| ViewCursorError::Item(V::ValidationError::from(error)))?;
        if suffix.len() == self.remaining.len() {
            return Err(ViewCursorError::EmptyItem);
        }
        view.validate().map_err(ViewCursorError::Item)?;
        self.remaining = suffix;
        Ok(Some(view))
    }
}

/// A committed leading output representation.
#[derive(Debug)]
pub struct Written<'output> {
    bytes: &'output mut [u8],
}

impl<'output> Written<'output> {
    /// Creates a committed wrapper.
    #[doc(hidden)]
    #[must_use]
    pub fn new(bytes: &'output mut [u8]) -> Self {
        Self { bytes }
    }

    /// Creates a wrapper for bytes just appended to an owned output buffer.
    #[cfg(feature = "bytes")]
    #[doc(hidden)]
    #[must_use]
    #[inline(always)]
    pub fn from_appended(output: &'output mut bytes::BytesMut, appended: usize) -> Self {
        let start = output.len().saturating_sub(appended);
        Self::new(&mut output[start..])
    }

    /// Returns committed bytes.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8] {
        self.bytes
    }

    /// Returns committed bytes mutably.
    #[must_use]
    pub fn as_bytes_mut(&mut self) -> &mut [u8] {
        self.bytes
    }

    /// Returns committed bytes.
    #[must_use]
    pub fn into_bytes(self) -> &'output mut [u8] {
        self.bytes
    }
}

/// Error returned by a prepare-and-commit convenience operation.
#[derive(Debug)]
pub enum BuildIntoError<E> {
    /// Preparation failed.
    Prepare(E),
    /// Output was too short.
    Output(OutputTooShortError),
}

impl<E: core::fmt::Display> core::fmt::Display for BuildIntoError<E> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Prepare(error) => write!(f, "wire preparation failed: {error}"),
            Self::Output(error) => error.fmt(f),
        }
    }
}

impl<E: core::fmt::Debug + core::fmt::Display> core::error::Error for BuildIntoError<E> {}

/// Prepares an atomic wire encoding.
pub trait WireEncode: Sized {
    /// Preparation error.
    type EncodeError: core::fmt::Debug + core::fmt::Display;

    /// Prepared plan.
    type Plan<'value>: PreparedLayout
    where
        Self: 'value;

    /// Prepares without output mutation.
    fn prepare<'value>(self) -> Result<Self::Plan<'value>, Self::EncodeError>
    where
        Self: 'value;
}
