//! Runtime contracts shared by `#[derive(Wire)]` implementations.

use crate::{OutputTooShortError, PreparedLayout};

/// A zero-sized marker for a raw semantic wire value computed during encoding.
pub struct Computed<T>(core::marker::PhantomData<fn() -> T>);

impl<T> core::fmt::Debug for Computed<T> {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        formatter.write_str("Computed")
    }
}

impl<T> PartialEq for Computed<T> {
    fn eq(&self, _: &Self) -> bool {
        true
    }
}

impl<T> Eq for Computed<T> {}

impl<T> Computed<T> {
    /// Creates a computed marker.
    #[must_use]
    pub const fn new() -> Self {
        Self(core::marker::PhantomData)
    }
}

impl<T> Default for Computed<T> {
    fn default() -> Self {
        Self::new()
    }
}

impl<T> Copy for Computed<T> {}

impl<T> Clone for Computed<T> {
    fn clone(&self) -> Self {
        *self
    }
}

/// Associates a semantic wire value with its generated read view.
#[doc(hidden)]
pub trait WireViewType {
    /// The typed failure returned while validating this representation.
    type DecodeError<'wire>: core::fmt::Debug + core::fmt::Display;

    /// The generated bytes-backed view for input with lifetime `'wire`.
    type View<'wire>: Copy + Clone;
}

/// A bytes-backed generated wire view.
#[doc(hidden)]
pub trait WireView<'wire>: Sized {
    /// The typed failure returned while validating the view.
    type DecodeError: core::fmt::Debug + core::fmt::Display;

    /// Validates one leading representation and creates its view.
    fn parse_view(input: &'wire [u8]) -> Result<(Self, &'wire [u8]), Self::DecodeError>;

    /// Builds this view's typed error for trailing input.
    fn trailing_bytes_error(represented: usize, input: usize) -> Self::DecodeError;

    /// Returns this view's exact represented bytes.
    fn as_bytes(&self) -> &'wire [u8];
}

/// Generated semantic validation for a structurally decoded view.
#[doc(hidden)]
pub trait WireViewValidation<'wire> {
    /// The human-owned validation error.
    type ValidationError: core::fmt::Debug + core::fmt::Display;

    /// Validates decoded field and model invariants.
    fn validate(&self) -> Result<(), Self::ValidationError>;
}

/// A request to frame one bytes-backed wire view.
#[doc(hidden)]
pub struct ViewRequest<'wire, V> {
    input: &'wire [u8],
    view: core::marker::PhantomData<V>,
}

/// A request which performs structural framing followed by semantic validation.
#[doc(hidden)]
pub struct ValidatedViewRequest<'wire, V> {
    input: &'wire [u8],
    view: core::marker::PhantomData<V>,
}

impl<'wire, V> ValidatedViewRequest<'wire, V> {
    /// Creates a validated view request.
    #[doc(hidden)]
    #[must_use]
    pub const fn new(input: &'wire [u8]) -> Self {
        Self {
            input,
            view: core::marker::PhantomData,
        }
    }

    /// Skips semantic validation and retains structural decode errors.
    #[must_use]
    pub const fn unchecked(self) -> ViewRequest<'wire, V> {
        ViewRequest::new(self.input)
    }
}

impl<'wire, V> ViewRequest<'wire, V> {
    /// Creates a view request.
    #[doc(hidden)]
    #[must_use]
    pub const fn new(input: &'wire [u8]) -> Self {
        Self {
            input,
            view: core::marker::PhantomData,
        }
    }
}

impl<'wire, V> ViewRequest<'wire, V>
where
    V: WireView<'wire>,
{
    /// Validates the leading representation and returns its unconsumed suffix.
    pub fn with_remainder(self) -> Result<(V, &'wire [u8]), V::DecodeError> {
        V::parse_view(self.input)
    }

    /// Validates one complete representation, rejecting trailing input.
    pub fn without_trailing(self) -> Result<V, V::DecodeError> {
        let input_len = self.input.len();
        let (view, suffix) = self.with_remainder()?;
        if suffix.is_empty() {
            Ok(view)
        } else {
            Err(V::trailing_bytes_error(view.as_bytes().len(), input_len))
        }
    }
}

impl<'wire, V> ValidatedViewRequest<'wire, V>
where
    V: WireView<'wire> + WireViewValidation<'wire>,
    V::ValidationError: From<V::DecodeError>,
{
    /// Frames and semantically validates the leading representation.
    pub fn with_remainder(self) -> Result<(V, &'wire [u8]), V::ValidationError> {
        let (view, remainder) = V::parse_view(self.input).map_err(V::ValidationError::from)?;
        view.validate()?;
        Ok((view, remainder))
    }

    /// Frames and semantically validates one complete representation.
    pub fn without_trailing(self) -> Result<V, V::ValidationError> {
        let input_len = self.input.len();
        let (view, suffix) = self.with_remainder()?;
        if suffix.is_empty() {
            Ok(view)
        } else {
            Err(V::ValidationError::from(V::trailing_bytes_error(
                view.as_bytes().len(),
                input_len,
            )))
        }
    }
}

/// Invalid framing for a sequence of fixed-width wire views.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FixedViewSequenceError {
    /// The generated item representation has zero width.
    InvalidItemWidth,
    /// Input ends with an incomplete item.
    TrailingPartialItem {
        /// Complete item width.
        item_width: usize,
        /// Bytes left after the last complete item.
        trailing: usize,
    },
}

impl core::fmt::Display for FixedViewSequenceError {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::InvalidItemWidth => {
                formatter.write_str("fixed sequence items must consume bytes")
            }
            Self::TrailingPartialItem {
                item_width,
                trailing,
            } => write!(
                formatter,
                "fixed sequence has {trailing} trailing bytes, fewer than one {item_width}-byte item",
            ),
        }
    }
}

impl core::error::Error for FixedViewSequenceError {}

/// Failure while framing or semantically validating a fixed-width view sequence.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FixedValidatedViewSequenceError<E> {
    /// Sequence framing failed.
    Framing(FixedViewSequenceError),
    /// An item failed semantic validation.
    Item(E),
}

impl<E: core::fmt::Display> core::fmt::Display for FixedValidatedViewSequenceError<E> {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Framing(error) => error.fmt(formatter),
            Self::Item(error) => error.fmt(formatter),
        }
    }
}

impl<E: core::fmt::Debug + core::fmt::Display> core::error::Error
    for FixedValidatedViewSequenceError<E>
{
}

/// An infallible iterator over preframed fixed-width wire views.
#[derive(Clone, Debug)]
pub struct FixedViewIterator<'wire, V> {
    chunks: core::slice::ChunksExact<'wire, u8>,
    make_view: fn(&'wire [u8]) -> V,
}

impl<'wire, V> FixedViewIterator<'wire, V> {
    /// Validates fixed-width sequence framing and creates its iterator.
    #[doc(hidden)]
    pub fn new(
        input: &'wire [u8],
        item_width: usize,
        make_view: fn(&'wire [u8]) -> V,
    ) -> Result<Self, FixedViewSequenceError> {
        if item_width == 0 {
            return Err(FixedViewSequenceError::InvalidItemWidth);
        }
        let chunks = input.chunks_exact(item_width);
        let trailing = chunks.remainder().len();
        if trailing != 0 {
            return Err(FixedViewSequenceError::TrailingPartialItem {
                item_width,
                trailing,
            });
        }
        Ok(Self { chunks, make_view })
    }
}

impl<'wire, V> Iterator for FixedViewIterator<'wire, V> {
    type Item = V;

    fn next(&mut self) -> Option<Self::Item> {
        self.chunks.next().map(self.make_view)
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        self.chunks.size_hint()
    }
}

impl<V> ExactSizeIterator for FixedViewIterator<'_, V> {
    fn len(&self) -> usize {
        self.chunks.len()
    }
}

impl<V> core::iter::FusedIterator for FixedViewIterator<'_, V> {}

/// Failure while advancing through a sequence of variable-width wire views.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ViewCursorError<E> {
    /// The next representation was structurally invalid.
    Item(E),
    /// A successful item consumed no bytes and therefore cannot advance a sequence.
    EmptyItem,
}

impl<E: core::fmt::Display> core::fmt::Display for ViewCursorError<E> {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Item(error) => error.fmt(formatter),
            Self::EmptyItem => formatter.write_str("a sequence item consumed no bytes"),
        }
    }
}

impl<E: core::fmt::Debug + core::fmt::Display> core::error::Error for ViewCursorError<E> {}

/// A fail-closed cursor over consecutive variable-width wire views.
#[derive(Clone, Copy, Debug)]
pub struct ViewCursor<'wire, V> {
    remaining: &'wire [u8],
    view: core::marker::PhantomData<V>,
}

impl<'wire, V> ViewCursor<'wire, V> {
    /// Creates a cursor over `input` without validating an item yet.
    #[doc(hidden)]
    #[must_use]
    pub const fn new(input: &'wire [u8]) -> Self {
        Self {
            remaining: input,
            view: core::marker::PhantomData,
        }
    }

    /// Returns the unconsumed bytes.
    #[must_use]
    pub const fn remaining(&self) -> &'wire [u8] {
        self.remaining
    }
}

impl<'wire, V> ViewCursor<'wire, V>
where
    V: WireView<'wire>,
{
    /// Validates and returns the next item, or `None` at the exact end.
    ///
    /// An error leaves the cursor at the failing item.
    #[allow(clippy::should_implement_trait)]
    pub fn next(&mut self) -> Result<Option<V>, ViewCursorError<V::DecodeError>> {
        if self.remaining.is_empty() {
            return Ok(None);
        }
        let (view, suffix) = V::parse_view(self.remaining).map_err(ViewCursorError::Item)?;
        if suffix.len() == self.remaining.len() {
            return Err(ViewCursorError::EmptyItem);
        }
        self.remaining = suffix;
        Ok(Some(view))
    }
}

/// A fail-closed cursor which semantically validates each framed item.
#[derive(Clone, Copy, Debug)]
pub struct ValidatedViewCursor<'wire, V> {
    remaining: &'wire [u8],
    view: core::marker::PhantomData<V>,
}

impl<'wire, V> ValidatedViewCursor<'wire, V> {
    /// Creates a validated cursor over `input` without framing an item yet.
    #[doc(hidden)]
    #[must_use]
    pub const fn new(input: &'wire [u8]) -> Self {
        Self {
            remaining: input,
            view: core::marker::PhantomData,
        }
    }

    /// Returns the unconsumed bytes.
    #[must_use]
    pub const fn remaining(&self) -> &'wire [u8] {
        self.remaining
    }

    /// Skips semantic validation for the remaining items.
    #[must_use]
    pub const fn unchecked(self) -> ViewCursor<'wire, V> {
        ViewCursor::new(self.remaining)
    }
}

impl<'wire, V> ValidatedViewCursor<'wire, V>
where
    V: WireView<'wire> + WireViewValidation<'wire>,
    V::ValidationError: From<V::DecodeError>,
{
    /// Validates and returns the next item, or `None` at the exact end.
    ///
    /// An error leaves the cursor at the failing item.
    #[allow(clippy::should_implement_trait)]
    pub fn next(&mut self) -> Result<Option<V>, ViewCursorError<V::ValidationError>> {
        if self.remaining.is_empty() {
            return Ok(None);
        }
        let (view, suffix) = V::parse_view(self.remaining)
            .map_err(|error| ViewCursorError::Item(V::ValidationError::from(error)))?;
        if suffix.len() == self.remaining.len() {
            return Err(ViewCursorError::EmptyItem);
        }
        view.validate().map_err(ViewCursorError::Item)?;
        self.remaining = suffix;
        Ok(Some(view))
    }
}

/// A committed leading output representation.
#[derive(Debug)]
pub struct Written<'output> {
    bytes: &'output mut [u8],
}

impl<'output> Written<'output> {
    /// Creates a committed wrapper.
    #[doc(hidden)]
    #[must_use]
    pub fn new(bytes: &'output mut [u8]) -> Self {
        Self { bytes }
    }

    /// Returns committed bytes.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8] {
        self.bytes
    }

    /// Returns committed bytes mutably.
    #[must_use]
    pub fn as_bytes_mut(&mut self) -> &mut [u8] {
        self.bytes
    }

    /// Returns committed bytes.
    #[must_use]
    pub fn into_bytes(self) -> &'output mut [u8] {
        self.bytes
    }
}

/// Error returned by a prepare-and-commit convenience operation.
#[derive(Debug)]
pub enum BuildIntoError<E> {
    /// Preparation failed.
    Prepare(E),
    /// Output was too short.
    Output(OutputTooShortError),
}

impl<E: core::fmt::Display> core::fmt::Display for BuildIntoError<E> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Prepare(error) => write!(f, "wire preparation failed: {error}"),
            Self::Output(error) => error.fmt(f),
        }
    }
}

impl<E: core::fmt::Debug + core::fmt::Display> core::error::Error for BuildIntoError<E> {}

/// Prepares an atomic wire encoding.
pub trait WireEncode: Sized {
    /// Preparation error.
    type EncodeError: core::fmt::Debug + core::fmt::Display;

    /// Prepared plan.
    type Plan<'value>: PreparedLayout
    where
        Self: 'value;

    /// Prepares without output mutation.
    fn prepare<'value>(self) -> Result<Self::Plan<'value>, Self::EncodeError>
    where
        Self: 'value;
}
