//! Runtime contracts shared by `#[derive(Wire)]` implementations.

use crate::{OutputTooShortError, PreparedLayout};

/// Associates a semantic wire value with its generated read view.
#[doc(hidden)]
pub trait WireViewType {
    /// The typed failure returned while validating this representation.
    type DecodeError<'wire>: core::fmt::Debug + core::fmt::Display;

    /// The generated bytes-backed view for input with lifetime `'wire`.
    type View<'wire>: Copy + Clone;
}

/// A bytes-backed generated wire view.
#[doc(hidden)]
pub trait WireView<'wire>: Sized {
    /// The typed failure returned while validating the view.
    type DecodeError: core::fmt::Debug + core::fmt::Display;

    /// Validates one leading representation and creates its view.
    fn parse_view(input: &'wire [u8]) -> Result<(Self, &'wire [u8]), Self::DecodeError>;

    /// Builds this view's typed error for trailing input.
    fn trailing_bytes_error(represented: usize, input: usize) -> Self::DecodeError;

    /// Returns this view's exact represented bytes.
    fn as_bytes(&self) -> &'wire [u8];
}

/// A request to frame one bytes-backed wire view.
#[doc(hidden)]
pub struct ViewRequest<'wire, V> {
    input: &'wire [u8],
    view: core::marker::PhantomData<V>,
}

impl<'wire, V> ViewRequest<'wire, V> {
    /// Creates a view request.
    #[doc(hidden)]
    #[must_use]
    pub const fn new(input: &'wire [u8]) -> Self {
        Self {
            input,
            view: core::marker::PhantomData,
        }
    }
}

impl<'wire, V> ViewRequest<'wire, V> {
    /// Supplies the opcode mapping required by this representation.
    #[must_use]
    pub const fn opcodes<O>(self, opcodes: &O) -> OpcodeViewRequest<'wire, '_, V, O> {
        OpcodeViewRequest {
            input: self.input,
            opcodes,
            view: core::marker::PhantomData,
        }
    }
}

/// A view request with its explicit opcode mapping.
#[doc(hidden)]
pub struct OpcodeViewRequest<'wire, 'opcodes, V, O> {
    input: &'wire [u8],
    opcodes: &'opcodes O,
    view: core::marker::PhantomData<V>,
}

/// Generated view composition through one concrete opcode mapping.
#[doc(hidden)]
pub trait WireViewWithOpcodes<'wire, O>: Sized {
    /// The typed failure returned while validating the view.
    type DecodeError: core::fmt::Debug + core::fmt::Display;

    /// Validates one leading representation with `opcodes`.
    fn parse_view_with_opcodes(
        input: &'wire [u8],
        opcodes: &O,
    ) -> Result<(Self, &'wire [u8]), Self::DecodeError>;

    /// Builds this view's typed error for trailing input.
    fn trailing_bytes_error(represented: usize, input: usize) -> Self::DecodeError;

    /// Returns this view's exact represented bytes.
    fn as_bytes(&self) -> &'wire [u8];
}

impl<'wire, V, O> OpcodeViewRequest<'wire, '_, V, O>
where
    V: WireViewWithOpcodes<'wire, O>,
{
    /// Validates the leading representation and returns its unconsumed suffix.
    pub fn with_remainder(self) -> Result<(V, &'wire [u8]), V::DecodeError> {
        V::parse_view_with_opcodes(self.input, self.opcodes)
    }

    /// Validates one complete representation, rejecting trailing input.
    pub fn without_trailing(self) -> Result<V, V::DecodeError> {
        let input_len = self.input.len();
        let (view, suffix) = self.with_remainder()?;
        if suffix.is_empty() {
            Ok(view)
        } else {
            Err(V::trailing_bytes_error(view.as_bytes().len(), input_len))
        }
    }
}

impl<'wire, V> ViewRequest<'wire, V>
where
    V: WireView<'wire>,
{
    /// Validates the leading representation and returns its unconsumed suffix.
    pub fn with_remainder(self) -> Result<(V, &'wire [u8]), V::DecodeError> {
        V::parse_view(self.input)
    }

    /// Validates one complete representation, rejecting trailing input.
    pub fn without_trailing(self) -> Result<V, V::DecodeError> {
        let input_len = self.input.len();
        let (view, suffix) = self.with_remainder()?;
        if suffix.is_empty() {
            Ok(view)
        } else {
            Err(V::trailing_bytes_error(view.as_bytes().len(), input_len))
        }
    }
}

/// Invalid framing for a sequence of fixed-width wire views.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FixedViewSequenceError {
    /// The generated item representation has zero width.
    InvalidItemWidth,
    /// Input ends with an incomplete item.
    TrailingPartialItem {
        /// Complete item width.
        item_width: usize,
        /// Bytes left after the last complete item.
        trailing: usize,
    },
}

impl core::fmt::Display for FixedViewSequenceError {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::InvalidItemWidth => {
                formatter.write_str("fixed sequence items must consume bytes")
            }
            Self::TrailingPartialItem {
                item_width,
                trailing,
            } => write!(
                formatter,
                "fixed sequence has {trailing} trailing bytes, fewer than one {item_width}-byte item",
            ),
        }
    }
}

impl core::error::Error for FixedViewSequenceError {}

/// An infallible iterator over preframed fixed-width wire views.
#[derive(Clone, Debug)]
pub struct FixedViewIterator<'wire, V> {
    chunks: core::slice::ChunksExact<'wire, u8>,
    make_view: fn(&'wire [u8]) -> V,
}

impl<'wire, V> FixedViewIterator<'wire, V> {
    /// Validates fixed-width sequence framing and creates its iterator.
    #[doc(hidden)]
    pub fn new(
        input: &'wire [u8],
        item_width: usize,
        make_view: fn(&'wire [u8]) -> V,
    ) -> Result<Self, FixedViewSequenceError> {
        if item_width == 0 {
            return Err(FixedViewSequenceError::InvalidItemWidth);
        }
        let chunks = input.chunks_exact(item_width);
        let trailing = chunks.remainder().len();
        if trailing != 0 {
            return Err(FixedViewSequenceError::TrailingPartialItem {
                item_width,
                trailing,
            });
        }
        Ok(Self { chunks, make_view })
    }
}

impl<'wire, V> Iterator for FixedViewIterator<'wire, V> {
    type Item = V;

    fn next(&mut self) -> Option<Self::Item> {
        self.chunks.next().map(self.make_view)
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        self.chunks.size_hint()
    }
}

impl<V> ExactSizeIterator for FixedViewIterator<'_, V> {
    fn len(&self) -> usize {
        self.chunks.len()
    }
}

impl<V> core::iter::FusedIterator for FixedViewIterator<'_, V> {}

/// Failure while advancing through a sequence of variable-width wire views.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ViewCursorError<E> {
    /// The next representation was structurally invalid.
    Item(E),
    /// A successful item consumed no bytes and therefore cannot advance a sequence.
    EmptyItem,
}

impl<E: core::fmt::Display> core::fmt::Display for ViewCursorError<E> {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Item(error) => error.fmt(formatter),
            Self::EmptyItem => formatter.write_str("a sequence item consumed no bytes"),
        }
    }
}

impl<E: core::fmt::Debug + core::fmt::Display> core::error::Error for ViewCursorError<E> {}

/// A fail-closed cursor over consecutive variable-width wire views.
#[derive(Clone, Copy, Debug)]
pub struct ViewCursor<'wire, V> {
    remaining: &'wire [u8],
    view: core::marker::PhantomData<V>,
}

impl<'wire, V> ViewCursor<'wire, V> {
    /// Creates a cursor over `input` without validating an item yet.
    #[doc(hidden)]
    #[must_use]
    pub const fn new(input: &'wire [u8]) -> Self {
        Self {
            remaining: input,
            view: core::marker::PhantomData,
        }
    }

    /// Returns the unconsumed bytes.
    #[must_use]
    pub const fn remaining(&self) -> &'wire [u8] {
        self.remaining
    }
}

impl<'wire, V> ViewCursor<'wire, V>
where
    V: WireView<'wire>,
{
    /// Validates and returns the next item, or `None` at the exact end.
    ///
    /// An error leaves the cursor at the failing item.
    #[allow(clippy::should_implement_trait)]
    pub fn next(&mut self) -> Result<Option<V>, ViewCursorError<V::DecodeError>> {
        if self.remaining.is_empty() {
            return Ok(None);
        }
        let (view, suffix) = V::parse_view(self.remaining).map_err(ViewCursorError::Item)?;
        if suffix.len() == self.remaining.len() {
            return Err(ViewCursorError::EmptyItem);
        }
        self.remaining = suffix;
        Ok(Some(view))
    }
}

/// A committed leading output representation.
#[derive(Debug)]
pub struct Written<'output> {
    bytes: &'output mut [u8],
}

impl<'output> Written<'output> {
    /// Creates a committed wrapper.
    #[doc(hidden)]
    #[must_use]
    pub fn new(bytes: &'output mut [u8]) -> Self {
        Self { bytes }
    }

    /// Returns committed bytes.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8] {
        self.bytes
    }

    /// Returns committed bytes mutably.
    #[must_use]
    pub fn as_bytes_mut(&mut self) -> &mut [u8] {
        self.bytes
    }

    /// Returns committed bytes.
    #[must_use]
    pub fn into_bytes(self) -> &'output mut [u8] {
        self.bytes
    }
}

/// Error returned by a prepare-and-commit convenience operation.
#[derive(Debug)]
pub enum BuildIntoError<E> {
    /// Preparation failed.
    Prepare(E),
    /// Output was too short.
    Output(OutputTooShortError),
}

impl<E: core::fmt::Display> core::fmt::Display for BuildIntoError<E> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Prepare(error) => write!(f, "wire preparation failed: {error}"),
            Self::Output(error) => error.fmt(f),
        }
    }
}

impl<E: core::fmt::Debug + core::fmt::Display> core::error::Error for BuildIntoError<E> {}

/// Prepares an atomic wire encoding.
pub trait WireEncode: Sized {
    /// Preparation error.
    type EncodeError: core::fmt::Debug + core::fmt::Display;

    /// Prepared plan.
    type Plan<'value>: PreparedLayout
    where
        Self: 'value;

    /// Prepares without output mutation.
    fn prepare<'value>(self) -> Result<Self::Plan<'value>, Self::EncodeError>
    where
        Self: 'value;
}

/// Generated encoding composition through one concrete opcode mapping.
#[doc(hidden)]
pub trait WireEncodeWithOpcodes<O>: Sized {
    /// Preparation error.
    type EncodeError: core::fmt::Debug + core::fmt::Display;

    /// Prepared plan that no longer depends on the opcode mapping.
    type Plan<'value>: PreparedLayout
    where
        Self: 'value;

    /// Resolves opcodes and prepares without output mutation.
    fn prepare_with_opcodes<'value>(
        self,
        opcodes: &O,
    ) -> Result<Self::Plan<'value>, Self::EncodeError>
    where
        Self: 'value;
}

/// A semantic write value paired with its explicit opcode mapping.
#[doc(hidden)]
pub struct OpcodeEncodeRequest<'opcodes, T, O> {
    value: T,
    opcodes: &'opcodes O,
}

impl<'opcodes, T, O> OpcodeEncodeRequest<'opcodes, T, O> {
    /// Creates an opcode-aware encoding request.
    #[doc(hidden)]
    #[must_use]
    pub const fn new(value: T, opcodes: &'opcodes O) -> Self {
        Self { value, opcodes }
    }
}

impl<T, O> OpcodeEncodeRequest<'_, T, O>
where
    T: WireEncodeWithOpcodes<O>,
{
    /// Resolves opcodes and prepares an atomic encoding.
    pub fn prepare<'value>(self) -> Result<T::Plan<'value>, T::EncodeError>
    where
        T: 'value,
    {
        T::prepare_with_opcodes(self.value, self.opcodes)
    }

    /// Resolves opcodes, prepares, and commits into `output`.
    pub fn build_into<'value, 'output>(
        self,
        output: &'output mut [u8],
    ) -> Result<(Written<'output>, &'output mut [u8]), BuildIntoError<T::EncodeError>>
    where
        T: 'value,
        T::Plan<'value>: for<'written> PreparedLayout<Written<'written> = Written<'written>>,
    {
        let plan: T::Plan<'value> = self.prepare().map_err(BuildIntoError::Prepare)?;
        PreparedLayout::commit_into(plan, output).map_err(BuildIntoError::Output)
    }
}
